# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 28fc77296bd7ad589268464ef3c0df99371278d9b789e2585cd6b9b0c88219403564d36cea75ba4a6df0780af11614f2558ece0f3e53cd3c39aed47c01d3c735

test:
  secret_key_base: 632a11de679805ace1352dffb86778afbf8ad7933846fbec2184e7edbfa2249b8e5e512acf593b44065e803e0ed700d5e7da3c3df942677f6b0ebcaf28bd7c3d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
